trigger:
- '*'

variables:
  buildConfiguration: 'Release'

stages:

- stage: Spinup
  jobs:
  - job: Spinup
    pool:
      vmImage: 'ubuntu-latest'

    variables: 
      AZURE_RESOURCE_GROUP: 'tailspin-space-game-rg'
      AZURE_SUBSCRIPTION_ID: '812866e1-7fdb-4a38-abda-bc40d7ffa85e'
      AZURE_WEBAPP_NAME: "tailspin-s-${fix}"
      AZURE_APP_PLAN: 'tailspin-space-game-asp'
      REGISTRY_NAME: "tailspin${fix}"

    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Azuresub99devend(812866e1-7fdb-4a38-abda-bc40d7ffa85e)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az configure --defaults location=westus2
          fix=$RANDOM
          az group create  --name $(AZURE_RESOURCE_GROUP) 
          az acr create --name $(REGISTRY_NAME) --resource-group $(AZURE_RESOURCE_GROUP) --sku standard --admin-enabled true
          az appservice plan create --resource-group $(AZURE_RESOURCE_GROUP) --name $(AZURE_APP_PLAN) --sku B1  --is-linux
          az webapp create --resource-group $(AZURE_RESOURCE_GROUP) --plan $(AZURE_APP_PLAN) --name $(AZURE_WEBAPP_NAME)  --deployment-container-image-name $REGISTRY_NAME.azurecr.io/web:latest